version: '3.8'
services:
  cache_server:
    image: redis:7.0.0-alpine
    hostname: redis1host
    restart: always
    ports:
     - '6379:6379'
    command: redis-server --bind 0.0.0.0
    volumes:
     - cache:/data1
    networks:
     - proxynet
    tty: true
  backend:
    build: ./server
    volumes: 
     - ./server:/app/server
    ports:
     - '8000:8000'
    tty: true
    depends_on:
     - cache_server
    command: npm run start:dev
    networks:
     - proxynet
  frontend:
    build: ./client
    volumes:
     - ./client:/app/client
    ports:
     - '80:80'
    tty: true
    depends_on:
      - cache_server
    networks:
     - proxynet
  
volumes:
 cache:
  driver: local
networks:
 proxynet:
  name: internal_network